version: '3.9'

services:
    web:
      build: .
      container_name: graphql-course
      restart: always      
      ports: 
            - "4000:4000"
      links: 
            - mymongodb
      volumes: 
            - .:/usr/src/app
    mymongodb: 
      container_name: mongodb
      image: mongo
      ports: 
            - "27018:27017"
      logging:
            driver: none
